---

- name: "VLAN Playbook"
  hosts: cisco
  connection: network_cli

  tasks:
    - name: "Push Cisco BGP Config"
      cisco.ios.ios_vlans:
        config:
        - name: FIVE
          vlan_id: 5
          state: active
          shutdown: disabled
        - name: TEN
          vlan_id: 10
          state: active
          shutdown: disabled
        state: merged
      register: cisco_output

    - name: "Print Cisco BGP Config"
      debug:
        msg: "{{ cisco_output }}"