---

- name: "Register Playbook"
  hosts: 192.168.1.11
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Push config"
      cisco.ios.ios_config:
        src: "ntp.j2"
      notify: ntp_handler_example
      register: ntp_result

  handlers:
    - name: ntp_handler_example
      debug:
        msg: "{{ ntp_result }}"