---

- name: "OSPF Playbook"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Push Cisco OSPF Config"
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: "{{ ospf.rid }}"
              network:
                - address: 13.14.15.0
                  wildcard_bits:  0.0.0.255
                  area: 13
                - address: 10.0.0.0
                  wildcard_bits: 0.0.0.255
                  area: 0
              default_information:
                originate: true
        state: merged
      register: cisco_output
      when: "ansible_network_os == 'cisco.ios.ios'"

    - name: "Print Cisco OSPF Config"
      debug:
        msg: "{{ cisco_output }}"
      when: "ansible_network_os == 'cisco.ios.ios'"