---
- name: "Play 1: Cisco Devices"
  hosts: cisco
  connection: network_cli

  tasks:
  - name: "Apply the provided configuration"
    cisco.ios.ios_logging_global:
      config:
        hosts:
          - hostname: "{{ item.ip }}"
      state: merged
    loop: "{{ syslog.hosts }}"
    when: item.port is not defined
    register: task1_output

  - name: 
    cisco.ios.ios_logging_global:
      config:
        hosts:
          - hostname: "{{ item.ip }}"
            transport:
              tcp:
                port: "{{ item.port }}"
      state: merged
    loop: "{{ syslog.hosts }}"
    when: item.port is defined
    register: task2_output

  - name: "Print Task 1"
    debug:
      msg: "{{ task1_output.results }}"

  - name: "Print Task 2"
    debug:
      msg: "{{ task2_output.results }}"