---

- name: "VLAN Playbook"
  hosts: vyos
  connection: network_cli

  tasks:
    - name: Create vlan
      vyos.vyos.vyos_vlan:
        aggregate:
          - vlan_id: 10
            name: vlan-10
            interfaces: eth1
            state: present
          - vlan_id: 33
            name: vlan-33
            interfaces: eth2
            state: present
          - vlan_id: 42
            name: vlan-42
            interfaces: eth3
            state: present
      register: vyos_output


    - name: "Print VyOS VLAN Config"
      debug:
        msg: "{{ vyos_output }}"