---

- name: "Test Playbook"
  hosts: localhost

  tasks:
    - name: "Collect facts about localhost"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"
          
    - name: "Recording Variable"
      set_fact:
        TD: "{{ ansible_date_time.date }}"

    - name: "Creating directories"
      file:
        path: "backups/{{ TD }}"
        state: directory
      run_once: true