---

- name: "Testing Genie"
  hosts: 192.168.1.11
  connection: network_cli

  tasks:
    - name: "Task 1 - Send a show command"
      cisco.ios.ios_command:
        commands: "show version"
      register: show_version_output

    - name: "Task 2 - Read in parse_genie role"
      include_role:
        name: clay584.parse_genie

    - name: "Task 3 - Parse show command"
      set_fact:
        parsed_data: >-
          {{ show_version_output.stdout[0] | parse_genie(command='show version', os='iosxe') }}

    - name: "Task 4 - Print output"
      debug:
        msg: "{{ parsed_data }}"
