---

- name: "Testing Genie"
  hosts: 192.168.1.11
  connection: network_cli

  tasks:
    - name: "Task 1 - Send a show command"
      cisco.ios.ios_command:
        commands: "show version"
      register: show_version_output

    - name: "Task 2 - Parse show command"
      set_fact:
        parsed_data: >-
          {{ show_version_output }}

    - name: "Task 3 - Print output"
      debug:
        msg: "{{ parsed_data }}"