---

- name: "VyOS Playbook"
  hosts: vyos
  connection: network_cli

  tasks:
    - name: "Remove banner configuration to VyOS"
      vyos.vyos.vyos_banner:
        banner: pre-login
        text: "CBT Nuggets banner for VyOS"
        state: absent

    - name: "Adding post-login VyOS banner"
      vyos.vyos.vyos_banner:
        banner: post-login
        text: "This is a post-login banner."
        state: present